name: LenRoot
version: '${project.version}'
main: eu.lenithia.lenroot.LenRoot

description: This is the root of Len!
authors: [Len]

api-version: '1.20'

commands:
  len:
    description: "Main command for LenRoot"
    usage: "/len <arg>"
    aliases: [lenroot, LenRoot]

  testkokot:
    description: "Test command for LenRoot"
    usage: "/testkokot <arg>"